/*
Binance Options API

OpenAPI specification for Binance cryptocurrency exchange - Options API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package options

import (
	"encoding/json"
)

// checks if the OptionsCreateCountdownCancelAllV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OptionsCreateCountdownCancelAllV1Resp{}

// OptionsCreateCountdownCancelAllV1Resp struct for OptionsCreateCountdownCancelAllV1Resp
type OptionsCreateCountdownCancelAllV1Resp struct {
	CountdownTime *int64 `json:"countdownTime,omitempty"`
	Underlying *string `json:"underlying,omitempty"`
}

// NewOptionsCreateCountdownCancelAllV1Resp instantiates a new OptionsCreateCountdownCancelAllV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOptionsCreateCountdownCancelAllV1Resp() *OptionsCreateCountdownCancelAllV1Resp {
	this := OptionsCreateCountdownCancelAllV1Resp{}
	return &this
}

// NewOptionsCreateCountdownCancelAllV1RespWithDefaults instantiates a new OptionsCreateCountdownCancelAllV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionsCreateCountdownCancelAllV1RespWithDefaults() *OptionsCreateCountdownCancelAllV1Resp {
	this := OptionsCreateCountdownCancelAllV1Resp{}
	return &this
}

// GetCountdownTime returns the CountdownTime field value if set, zero value otherwise.
func (o *OptionsCreateCountdownCancelAllV1Resp) GetCountdownTime() int64 {
	if o == nil || IsNil(o.CountdownTime) {
		var ret int64
		return ret
	}
	return *o.CountdownTime
}

// GetCountdownTimeOk returns a tuple with the CountdownTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionsCreateCountdownCancelAllV1Resp) GetCountdownTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.CountdownTime) {
		return nil, false
	}
	return o.CountdownTime, true
}

// HasCountdownTime returns a boolean if a field has been set.
func (o *OptionsCreateCountdownCancelAllV1Resp) HasCountdownTime() bool {
	if o != nil && !IsNil(o.CountdownTime) {
		return true
	}

	return false
}

// SetCountdownTime gets a reference to the given int64 and assigns it to the CountdownTime field.
func (o *OptionsCreateCountdownCancelAllV1Resp) SetCountdownTime(v int64) {
	o.CountdownTime = &v
}

// GetUnderlying returns the Underlying field value if set, zero value otherwise.
func (o *OptionsCreateCountdownCancelAllV1Resp) GetUnderlying() string {
	if o == nil || IsNil(o.Underlying) {
		var ret string
		return ret
	}
	return *o.Underlying
}

// GetUnderlyingOk returns a tuple with the Underlying field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionsCreateCountdownCancelAllV1Resp) GetUnderlyingOk() (*string, bool) {
	if o == nil || IsNil(o.Underlying) {
		return nil, false
	}
	return o.Underlying, true
}

// HasUnderlying returns a boolean if a field has been set.
func (o *OptionsCreateCountdownCancelAllV1Resp) HasUnderlying() bool {
	if o != nil && !IsNil(o.Underlying) {
		return true
	}

	return false
}

// SetUnderlying gets a reference to the given string and assigns it to the Underlying field.
func (o *OptionsCreateCountdownCancelAllV1Resp) SetUnderlying(v string) {
	o.Underlying = &v
}

func (o OptionsCreateCountdownCancelAllV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OptionsCreateCountdownCancelAllV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CountdownTime) {
		toSerialize["countdownTime"] = o.CountdownTime
	}
	if !IsNil(o.Underlying) {
		toSerialize["underlying"] = o.Underlying
	}
	return toSerialize, nil
}

type NullableOptionsCreateCountdownCancelAllV1Resp struct {
	value *OptionsCreateCountdownCancelAllV1Resp
	isSet bool
}

func (v NullableOptionsCreateCountdownCancelAllV1Resp) Get() *OptionsCreateCountdownCancelAllV1Resp {
	return v.value
}

func (v *NullableOptionsCreateCountdownCancelAllV1Resp) Set(val *OptionsCreateCountdownCancelAllV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableOptionsCreateCountdownCancelAllV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableOptionsCreateCountdownCancelAllV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptionsCreateCountdownCancelAllV1Resp(val *OptionsCreateCountdownCancelAllV1Resp) *NullableOptionsCreateCountdownCancelAllV1Resp {
	return &NullableOptionsCreateCountdownCancelAllV1Resp{value: val, isSet: true}
}

func (v NullableOptionsCreateCountdownCancelAllV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptionsCreateCountdownCancelAllV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


