/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the DeleteMarginIsolatedAccountV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteMarginIsolatedAccountV1Resp{}

// DeleteMarginIsolatedAccountV1Resp struct for DeleteMarginIsolatedAccountV1Resp
type DeleteMarginIsolatedAccountV1Resp struct {
	Success *bool `json:"success,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
}

// NewDeleteMarginIsolatedAccountV1Resp instantiates a new DeleteMarginIsolatedAccountV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteMarginIsolatedAccountV1Resp() *DeleteMarginIsolatedAccountV1Resp {
	this := DeleteMarginIsolatedAccountV1Resp{}
	return &this
}

// NewDeleteMarginIsolatedAccountV1RespWithDefaults instantiates a new DeleteMarginIsolatedAccountV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteMarginIsolatedAccountV1RespWithDefaults() *DeleteMarginIsolatedAccountV1Resp {
	this := DeleteMarginIsolatedAccountV1Resp{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *DeleteMarginIsolatedAccountV1Resp) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteMarginIsolatedAccountV1Resp) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *DeleteMarginIsolatedAccountV1Resp) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *DeleteMarginIsolatedAccountV1Resp) SetSuccess(v bool) {
	o.Success = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *DeleteMarginIsolatedAccountV1Resp) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteMarginIsolatedAccountV1Resp) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *DeleteMarginIsolatedAccountV1Resp) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *DeleteMarginIsolatedAccountV1Resp) SetSymbol(v string) {
	o.Symbol = &v
}

func (o DeleteMarginIsolatedAccountV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteMarginIsolatedAccountV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	return toSerialize, nil
}

type NullableDeleteMarginIsolatedAccountV1Resp struct {
	value *DeleteMarginIsolatedAccountV1Resp
	isSet bool
}

func (v NullableDeleteMarginIsolatedAccountV1Resp) Get() *DeleteMarginIsolatedAccountV1Resp {
	return v.value
}

func (v *NullableDeleteMarginIsolatedAccountV1Resp) Set(val *DeleteMarginIsolatedAccountV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteMarginIsolatedAccountV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteMarginIsolatedAccountV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteMarginIsolatedAccountV1Resp(val *DeleteMarginIsolatedAccountV1Resp) *NullableDeleteMarginIsolatedAccountV1Resp {
	return &NullableDeleteMarginIsolatedAccountV1Resp{value: val, isSet: true}
}

func (v NullableDeleteMarginIsolatedAccountV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteMarginIsolatedAccountV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


