/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the GetMiningPubCoinListV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiningPubCoinListV1Resp{}

// GetMiningPubCoinListV1Resp struct for GetMiningPubCoinListV1Resp
type GetMiningPubCoinListV1Resp struct {
	Code *int32 `json:"code,omitempty"`
	Data []GetMiningPubCoinListV1RespDataInner `json:"data,omitempty"`
	Msg *string `json:"msg,omitempty"`
}

// NewGetMiningPubCoinListV1Resp instantiates a new GetMiningPubCoinListV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiningPubCoinListV1Resp() *GetMiningPubCoinListV1Resp {
	this := GetMiningPubCoinListV1Resp{}
	return &this
}

// NewGetMiningPubCoinListV1RespWithDefaults instantiates a new GetMiningPubCoinListV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiningPubCoinListV1RespWithDefaults() *GetMiningPubCoinListV1Resp {
	this := GetMiningPubCoinListV1Resp{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetMiningPubCoinListV1Resp) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiningPubCoinListV1Resp) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetMiningPubCoinListV1Resp) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *GetMiningPubCoinListV1Resp) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetMiningPubCoinListV1Resp) GetData() []GetMiningPubCoinListV1RespDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetMiningPubCoinListV1RespDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiningPubCoinListV1Resp) GetDataOk() ([]GetMiningPubCoinListV1RespDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetMiningPubCoinListV1Resp) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetMiningPubCoinListV1RespDataInner and assigns it to the Data field.
func (o *GetMiningPubCoinListV1Resp) SetData(v []GetMiningPubCoinListV1RespDataInner) {
	o.Data = v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *GetMiningPubCoinListV1Resp) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiningPubCoinListV1Resp) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *GetMiningPubCoinListV1Resp) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *GetMiningPubCoinListV1Resp) SetMsg(v string) {
	o.Msg = &v
}

func (o GetMiningPubCoinListV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiningPubCoinListV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableGetMiningPubCoinListV1Resp struct {
	value *GetMiningPubCoinListV1Resp
	isSet bool
}

func (v NullableGetMiningPubCoinListV1Resp) Get() *GetMiningPubCoinListV1Resp {
	return v.value
}

func (v *NullableGetMiningPubCoinListV1Resp) Set(val *GetMiningPubCoinListV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiningPubCoinListV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiningPubCoinListV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiningPubCoinListV1Resp(val *GetMiningPubCoinListV1Resp) *NullableGetMiningPubCoinListV1Resp {
	return &NullableGetMiningPubCoinListV1Resp{value: val, isSet: true}
}

func (v NullableGetMiningPubCoinListV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiningPubCoinListV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


