/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the CreateUserDataStreamV3Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserDataStreamV3Resp{}

// CreateUserDataStreamV3Resp struct for CreateUserDataStreamV3Resp
type CreateUserDataStreamV3Resp struct {
	ListenKey *string `json:"listenKey,omitempty"`
}

// NewCreateUserDataStreamV3Resp instantiates a new CreateUserDataStreamV3Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserDataStreamV3Resp() *CreateUserDataStreamV3Resp {
	this := CreateUserDataStreamV3Resp{}
	return &this
}

// NewCreateUserDataStreamV3RespWithDefaults instantiates a new CreateUserDataStreamV3Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserDataStreamV3RespWithDefaults() *CreateUserDataStreamV3Resp {
	this := CreateUserDataStreamV3Resp{}
	return &this
}

// GetListenKey returns the ListenKey field value if set, zero value otherwise.
func (o *CreateUserDataStreamV3Resp) GetListenKey() string {
	if o == nil || IsNil(o.ListenKey) {
		var ret string
		return ret
	}
	return *o.ListenKey
}

// GetListenKeyOk returns a tuple with the ListenKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserDataStreamV3Resp) GetListenKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ListenKey) {
		return nil, false
	}
	return o.ListenKey, true
}

// HasListenKey returns a boolean if a field has been set.
func (o *CreateUserDataStreamV3Resp) HasListenKey() bool {
	if o != nil && !IsNil(o.ListenKey) {
		return true
	}

	return false
}

// SetListenKey gets a reference to the given string and assigns it to the ListenKey field.
func (o *CreateUserDataStreamV3Resp) SetListenKey(v string) {
	o.ListenKey = &v
}

func (o CreateUserDataStreamV3Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserDataStreamV3Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ListenKey) {
		toSerialize["listenKey"] = o.ListenKey
	}
	return toSerialize, nil
}

type NullableCreateUserDataStreamV3Resp struct {
	value *CreateUserDataStreamV3Resp
	isSet bool
}

func (v NullableCreateUserDataStreamV3Resp) Get() *CreateUserDataStreamV3Resp {
	return v.value
}

func (v *NullableCreateUserDataStreamV3Resp) Set(val *CreateUserDataStreamV3Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserDataStreamV3Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserDataStreamV3Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserDataStreamV3Resp(val *CreateUserDataStreamV3Resp) *NullableCreateUserDataStreamV3Resp {
	return &NullableCreateUserDataStreamV3Resp{value: val, isSet: true}
}

func (v NullableCreateUserDataStreamV3Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserDataStreamV3Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


