/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the GetBrokerSubAccountMarginSummaryV1RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBrokerSubAccountMarginSummaryV1RespDataInner{}

// GetBrokerSubAccountMarginSummaryV1RespDataInner struct for GetBrokerSubAccountMarginSummaryV1RespDataInner
type GetBrokerSubAccountMarginSummaryV1RespDataInner struct {
	MarginEnable *bool `json:"marginEnable,omitempty"`
	MarginLevel *string `json:"marginLevel,omitempty"`
	SubAccountId *string `json:"subAccountId,omitempty"`
	TotalAssetOfBtc *string `json:"totalAssetOfBtc,omitempty"`
	TotalLiabilityOfBtc *string `json:"totalLiabilityOfBtc,omitempty"`
	TotalNetAssetOfBtc *string `json:"totalNetAssetOfBtc,omitempty"`
}

// NewGetBrokerSubAccountMarginSummaryV1RespDataInner instantiates a new GetBrokerSubAccountMarginSummaryV1RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBrokerSubAccountMarginSummaryV1RespDataInner() *GetBrokerSubAccountMarginSummaryV1RespDataInner {
	this := GetBrokerSubAccountMarginSummaryV1RespDataInner{}
	return &this
}

// NewGetBrokerSubAccountMarginSummaryV1RespDataInnerWithDefaults instantiates a new GetBrokerSubAccountMarginSummaryV1RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBrokerSubAccountMarginSummaryV1RespDataInnerWithDefaults() *GetBrokerSubAccountMarginSummaryV1RespDataInner {
	this := GetBrokerSubAccountMarginSummaryV1RespDataInner{}
	return &this
}

// GetMarginEnable returns the MarginEnable field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetMarginEnable() bool {
	if o == nil || IsNil(o.MarginEnable) {
		var ret bool
		return ret
	}
	return *o.MarginEnable
}

// GetMarginEnableOk returns a tuple with the MarginEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetMarginEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.MarginEnable) {
		return nil, false
	}
	return o.MarginEnable, true
}

// HasMarginEnable returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) HasMarginEnable() bool {
	if o != nil && !IsNil(o.MarginEnable) {
		return true
	}

	return false
}

// SetMarginEnable gets a reference to the given bool and assigns it to the MarginEnable field.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) SetMarginEnable(v bool) {
	o.MarginEnable = &v
}

// GetMarginLevel returns the MarginLevel field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetMarginLevel() string {
	if o == nil || IsNil(o.MarginLevel) {
		var ret string
		return ret
	}
	return *o.MarginLevel
}

// GetMarginLevelOk returns a tuple with the MarginLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetMarginLevelOk() (*string, bool) {
	if o == nil || IsNil(o.MarginLevel) {
		return nil, false
	}
	return o.MarginLevel, true
}

// HasMarginLevel returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) HasMarginLevel() bool {
	if o != nil && !IsNil(o.MarginLevel) {
		return true
	}

	return false
}

// SetMarginLevel gets a reference to the given string and assigns it to the MarginLevel field.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) SetMarginLevel(v string) {
	o.MarginLevel = &v
}

// GetSubAccountId returns the SubAccountId field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetSubAccountId() string {
	if o == nil || IsNil(o.SubAccountId) {
		var ret string
		return ret
	}
	return *o.SubAccountId
}

// GetSubAccountIdOk returns a tuple with the SubAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetSubAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubAccountId) {
		return nil, false
	}
	return o.SubAccountId, true
}

// HasSubAccountId returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) HasSubAccountId() bool {
	if o != nil && !IsNil(o.SubAccountId) {
		return true
	}

	return false
}

// SetSubAccountId gets a reference to the given string and assigns it to the SubAccountId field.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) SetSubAccountId(v string) {
	o.SubAccountId = &v
}

// GetTotalAssetOfBtc returns the TotalAssetOfBtc field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetTotalAssetOfBtc() string {
	if o == nil || IsNil(o.TotalAssetOfBtc) {
		var ret string
		return ret
	}
	return *o.TotalAssetOfBtc
}

// GetTotalAssetOfBtcOk returns a tuple with the TotalAssetOfBtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetTotalAssetOfBtcOk() (*string, bool) {
	if o == nil || IsNil(o.TotalAssetOfBtc) {
		return nil, false
	}
	return o.TotalAssetOfBtc, true
}

// HasTotalAssetOfBtc returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) HasTotalAssetOfBtc() bool {
	if o != nil && !IsNil(o.TotalAssetOfBtc) {
		return true
	}

	return false
}

// SetTotalAssetOfBtc gets a reference to the given string and assigns it to the TotalAssetOfBtc field.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) SetTotalAssetOfBtc(v string) {
	o.TotalAssetOfBtc = &v
}

// GetTotalLiabilityOfBtc returns the TotalLiabilityOfBtc field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetTotalLiabilityOfBtc() string {
	if o == nil || IsNil(o.TotalLiabilityOfBtc) {
		var ret string
		return ret
	}
	return *o.TotalLiabilityOfBtc
}

// GetTotalLiabilityOfBtcOk returns a tuple with the TotalLiabilityOfBtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetTotalLiabilityOfBtcOk() (*string, bool) {
	if o == nil || IsNil(o.TotalLiabilityOfBtc) {
		return nil, false
	}
	return o.TotalLiabilityOfBtc, true
}

// HasTotalLiabilityOfBtc returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) HasTotalLiabilityOfBtc() bool {
	if o != nil && !IsNil(o.TotalLiabilityOfBtc) {
		return true
	}

	return false
}

// SetTotalLiabilityOfBtc gets a reference to the given string and assigns it to the TotalLiabilityOfBtc field.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) SetTotalLiabilityOfBtc(v string) {
	o.TotalLiabilityOfBtc = &v
}

// GetTotalNetAssetOfBtc returns the TotalNetAssetOfBtc field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetTotalNetAssetOfBtc() string {
	if o == nil || IsNil(o.TotalNetAssetOfBtc) {
		var ret string
		return ret
	}
	return *o.TotalNetAssetOfBtc
}

// GetTotalNetAssetOfBtcOk returns a tuple with the TotalNetAssetOfBtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) GetTotalNetAssetOfBtcOk() (*string, bool) {
	if o == nil || IsNil(o.TotalNetAssetOfBtc) {
		return nil, false
	}
	return o.TotalNetAssetOfBtc, true
}

// HasTotalNetAssetOfBtc returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) HasTotalNetAssetOfBtc() bool {
	if o != nil && !IsNil(o.TotalNetAssetOfBtc) {
		return true
	}

	return false
}

// SetTotalNetAssetOfBtc gets a reference to the given string and assigns it to the TotalNetAssetOfBtc field.
func (o *GetBrokerSubAccountMarginSummaryV1RespDataInner) SetTotalNetAssetOfBtc(v string) {
	o.TotalNetAssetOfBtc = &v
}

func (o GetBrokerSubAccountMarginSummaryV1RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBrokerSubAccountMarginSummaryV1RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MarginEnable) {
		toSerialize["marginEnable"] = o.MarginEnable
	}
	if !IsNil(o.MarginLevel) {
		toSerialize["marginLevel"] = o.MarginLevel
	}
	if !IsNil(o.SubAccountId) {
		toSerialize["subAccountId"] = o.SubAccountId
	}
	if !IsNil(o.TotalAssetOfBtc) {
		toSerialize["totalAssetOfBtc"] = o.TotalAssetOfBtc
	}
	if !IsNil(o.TotalLiabilityOfBtc) {
		toSerialize["totalLiabilityOfBtc"] = o.TotalLiabilityOfBtc
	}
	if !IsNil(o.TotalNetAssetOfBtc) {
		toSerialize["totalNetAssetOfBtc"] = o.TotalNetAssetOfBtc
	}
	return toSerialize, nil
}

type NullableGetBrokerSubAccountMarginSummaryV1RespDataInner struct {
	value *GetBrokerSubAccountMarginSummaryV1RespDataInner
	isSet bool
}

func (v NullableGetBrokerSubAccountMarginSummaryV1RespDataInner) Get() *GetBrokerSubAccountMarginSummaryV1RespDataInner {
	return v.value
}

func (v *NullableGetBrokerSubAccountMarginSummaryV1RespDataInner) Set(val *GetBrokerSubAccountMarginSummaryV1RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBrokerSubAccountMarginSummaryV1RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBrokerSubAccountMarginSummaryV1RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBrokerSubAccountMarginSummaryV1RespDataInner(val *GetBrokerSubAccountMarginSummaryV1RespDataInner) *NullableGetBrokerSubAccountMarginSummaryV1RespDataInner {
	return &NullableGetBrokerSubAccountMarginSummaryV1RespDataInner{value: val, isSet: true}
}

func (v NullableGetBrokerSubAccountMarginSummaryV1RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBrokerSubAccountMarginSummaryV1RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


