/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the GetMarginTransferV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMarginTransferV1Resp{}

// GetMarginTransferV1Resp struct for GetMarginTransferV1Resp
type GetMarginTransferV1Resp struct {
	Rows []GetMarginTransferV1RespRowsInner `json:"rows,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewGetMarginTransferV1Resp instantiates a new GetMarginTransferV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMarginTransferV1Resp() *GetMarginTransferV1Resp {
	this := GetMarginTransferV1Resp{}
	return &this
}

// NewGetMarginTransferV1RespWithDefaults instantiates a new GetMarginTransferV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMarginTransferV1RespWithDefaults() *GetMarginTransferV1Resp {
	this := GetMarginTransferV1Resp{}
	return &this
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *GetMarginTransferV1Resp) GetRows() []GetMarginTransferV1RespRowsInner {
	if o == nil || IsNil(o.Rows) {
		var ret []GetMarginTransferV1RespRowsInner
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMarginTransferV1Resp) GetRowsOk() ([]GetMarginTransferV1RespRowsInner, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *GetMarginTransferV1Resp) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []GetMarginTransferV1RespRowsInner and assigns it to the Rows field.
func (o *GetMarginTransferV1Resp) SetRows(v []GetMarginTransferV1RespRowsInner) {
	o.Rows = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetMarginTransferV1Resp) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMarginTransferV1Resp) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetMarginTransferV1Resp) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetMarginTransferV1Resp) SetTotal(v int32) {
	o.Total = &v
}

func (o GetMarginTransferV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMarginTransferV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableGetMarginTransferV1Resp struct {
	value *GetMarginTransferV1Resp
	isSet bool
}

func (v NullableGetMarginTransferV1Resp) Get() *GetMarginTransferV1Resp {
	return v.value
}

func (v *NullableGetMarginTransferV1Resp) Set(val *GetMarginTransferV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMarginTransferV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMarginTransferV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMarginTransferV1Resp(val *GetMarginTransferV1Resp) *NullableGetMarginTransferV1Resp {
	return &NullableGetMarginTransferV1Resp{value: val, isSet: true}
}

func (v NullableGetMarginTransferV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMarginTransferV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


