/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the GetBrokerSubAccountMarginSummaryV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBrokerSubAccountMarginSummaryV1Resp{}

// GetBrokerSubAccountMarginSummaryV1Resp struct for GetBrokerSubAccountMarginSummaryV1Resp
type GetBrokerSubAccountMarginSummaryV1Resp struct {
	Data []GetBrokerSubAccountMarginSummaryV1RespDataInner `json:"data,omitempty"`
	Timestamp *int64 `json:"timestamp,omitempty"`
}

// NewGetBrokerSubAccountMarginSummaryV1Resp instantiates a new GetBrokerSubAccountMarginSummaryV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBrokerSubAccountMarginSummaryV1Resp() *GetBrokerSubAccountMarginSummaryV1Resp {
	this := GetBrokerSubAccountMarginSummaryV1Resp{}
	return &this
}

// NewGetBrokerSubAccountMarginSummaryV1RespWithDefaults instantiates a new GetBrokerSubAccountMarginSummaryV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBrokerSubAccountMarginSummaryV1RespWithDefaults() *GetBrokerSubAccountMarginSummaryV1Resp {
	this := GetBrokerSubAccountMarginSummaryV1Resp{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) GetData() []GetBrokerSubAccountMarginSummaryV1RespDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetBrokerSubAccountMarginSummaryV1RespDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) GetDataOk() ([]GetBrokerSubAccountMarginSummaryV1RespDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetBrokerSubAccountMarginSummaryV1RespDataInner and assigns it to the Data field.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) SetData(v []GetBrokerSubAccountMarginSummaryV1RespDataInner) {
	o.Data = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) GetTimestamp() int64 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int64
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) GetTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int64 and assigns it to the Timestamp field.
func (o *GetBrokerSubAccountMarginSummaryV1Resp) SetTimestamp(v int64) {
	o.Timestamp = &v
}

func (o GetBrokerSubAccountMarginSummaryV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBrokerSubAccountMarginSummaryV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableGetBrokerSubAccountMarginSummaryV1Resp struct {
	value *GetBrokerSubAccountMarginSummaryV1Resp
	isSet bool
}

func (v NullableGetBrokerSubAccountMarginSummaryV1Resp) Get() *GetBrokerSubAccountMarginSummaryV1Resp {
	return v.value
}

func (v *NullableGetBrokerSubAccountMarginSummaryV1Resp) Set(val *GetBrokerSubAccountMarginSummaryV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBrokerSubAccountMarginSummaryV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBrokerSubAccountMarginSummaryV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBrokerSubAccountMarginSummaryV1Resp(val *GetBrokerSubAccountMarginSummaryV1Resp) *NullableGetBrokerSubAccountMarginSummaryV1Resp {
	return &NullableGetBrokerSubAccountMarginSummaryV1Resp{value: val, isSet: true}
}

func (v NullableGetBrokerSubAccountMarginSummaryV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBrokerSubAccountMarginSummaryV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


