/*
Binance Sub Account API

OpenAPI specification for Binance exchange - Subaccount API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package subaccount

import (
	"encoding/json"
)

// checks if the SubaccountGetSubAccountMarginAccountV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubaccountGetSubAccountMarginAccountV1Resp{}

// SubaccountGetSubAccountMarginAccountV1Resp struct for SubaccountGetSubAccountMarginAccountV1Resp
type SubaccountGetSubAccountMarginAccountV1Resp struct {
	Email *string `json:"email,omitempty"`
	MarginLevel *string `json:"marginLevel,omitempty"`
	MarginTradeCoeffVo *SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo `json:"marginTradeCoeffVo,omitempty"`
	MarginUserAssetVoList []SubaccountGetManagedSubaccountMarginAssetV1RespUserAssetsInner `json:"marginUserAssetVoList,omitempty"`
	TotalAssetOfBtc *string `json:"totalAssetOfBtc,omitempty"`
	TotalLiabilityOfBtc *string `json:"totalLiabilityOfBtc,omitempty"`
	TotalNetAssetOfBtc *string `json:"totalNetAssetOfBtc,omitempty"`
}

// NewSubaccountGetSubAccountMarginAccountV1Resp instantiates a new SubaccountGetSubAccountMarginAccountV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubaccountGetSubAccountMarginAccountV1Resp() *SubaccountGetSubAccountMarginAccountV1Resp {
	this := SubaccountGetSubAccountMarginAccountV1Resp{}
	return &this
}

// NewSubaccountGetSubAccountMarginAccountV1RespWithDefaults instantiates a new SubaccountGetSubAccountMarginAccountV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubaccountGetSubAccountMarginAccountV1RespWithDefaults() *SubaccountGetSubAccountMarginAccountV1Resp {
	this := SubaccountGetSubAccountMarginAccountV1Resp{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetEmail(v string) {
	o.Email = &v
}

// GetMarginLevel returns the MarginLevel field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetMarginLevel() string {
	if o == nil || IsNil(o.MarginLevel) {
		var ret string
		return ret
	}
	return *o.MarginLevel
}

// GetMarginLevelOk returns a tuple with the MarginLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetMarginLevelOk() (*string, bool) {
	if o == nil || IsNil(o.MarginLevel) {
		return nil, false
	}
	return o.MarginLevel, true
}

// HasMarginLevel returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasMarginLevel() bool {
	if o != nil && !IsNil(o.MarginLevel) {
		return true
	}

	return false
}

// SetMarginLevel gets a reference to the given string and assigns it to the MarginLevel field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetMarginLevel(v string) {
	o.MarginLevel = &v
}

// GetMarginTradeCoeffVo returns the MarginTradeCoeffVo field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetMarginTradeCoeffVo() SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo {
	if o == nil || IsNil(o.MarginTradeCoeffVo) {
		var ret SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo
		return ret
	}
	return *o.MarginTradeCoeffVo
}

// GetMarginTradeCoeffVoOk returns a tuple with the MarginTradeCoeffVo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetMarginTradeCoeffVoOk() (*SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo, bool) {
	if o == nil || IsNil(o.MarginTradeCoeffVo) {
		return nil, false
	}
	return o.MarginTradeCoeffVo, true
}

// HasMarginTradeCoeffVo returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasMarginTradeCoeffVo() bool {
	if o != nil && !IsNil(o.MarginTradeCoeffVo) {
		return true
	}

	return false
}

// SetMarginTradeCoeffVo gets a reference to the given SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo and assigns it to the MarginTradeCoeffVo field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetMarginTradeCoeffVo(v SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo) {
	o.MarginTradeCoeffVo = &v
}

// GetMarginUserAssetVoList returns the MarginUserAssetVoList field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetMarginUserAssetVoList() []SubaccountGetManagedSubaccountMarginAssetV1RespUserAssetsInner {
	if o == nil || IsNil(o.MarginUserAssetVoList) {
		var ret []SubaccountGetManagedSubaccountMarginAssetV1RespUserAssetsInner
		return ret
	}
	return o.MarginUserAssetVoList
}

// GetMarginUserAssetVoListOk returns a tuple with the MarginUserAssetVoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetMarginUserAssetVoListOk() ([]SubaccountGetManagedSubaccountMarginAssetV1RespUserAssetsInner, bool) {
	if o == nil || IsNil(o.MarginUserAssetVoList) {
		return nil, false
	}
	return o.MarginUserAssetVoList, true
}

// HasMarginUserAssetVoList returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasMarginUserAssetVoList() bool {
	if o != nil && !IsNil(o.MarginUserAssetVoList) {
		return true
	}

	return false
}

// SetMarginUserAssetVoList gets a reference to the given []SubaccountGetManagedSubaccountMarginAssetV1RespUserAssetsInner and assigns it to the MarginUserAssetVoList field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetMarginUserAssetVoList(v []SubaccountGetManagedSubaccountMarginAssetV1RespUserAssetsInner) {
	o.MarginUserAssetVoList = v
}

// GetTotalAssetOfBtc returns the TotalAssetOfBtc field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetTotalAssetOfBtc() string {
	if o == nil || IsNil(o.TotalAssetOfBtc) {
		var ret string
		return ret
	}
	return *o.TotalAssetOfBtc
}

// GetTotalAssetOfBtcOk returns a tuple with the TotalAssetOfBtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetTotalAssetOfBtcOk() (*string, bool) {
	if o == nil || IsNil(o.TotalAssetOfBtc) {
		return nil, false
	}
	return o.TotalAssetOfBtc, true
}

// HasTotalAssetOfBtc returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasTotalAssetOfBtc() bool {
	if o != nil && !IsNil(o.TotalAssetOfBtc) {
		return true
	}

	return false
}

// SetTotalAssetOfBtc gets a reference to the given string and assigns it to the TotalAssetOfBtc field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetTotalAssetOfBtc(v string) {
	o.TotalAssetOfBtc = &v
}

// GetTotalLiabilityOfBtc returns the TotalLiabilityOfBtc field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetTotalLiabilityOfBtc() string {
	if o == nil || IsNil(o.TotalLiabilityOfBtc) {
		var ret string
		return ret
	}
	return *o.TotalLiabilityOfBtc
}

// GetTotalLiabilityOfBtcOk returns a tuple with the TotalLiabilityOfBtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetTotalLiabilityOfBtcOk() (*string, bool) {
	if o == nil || IsNil(o.TotalLiabilityOfBtc) {
		return nil, false
	}
	return o.TotalLiabilityOfBtc, true
}

// HasTotalLiabilityOfBtc returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasTotalLiabilityOfBtc() bool {
	if o != nil && !IsNil(o.TotalLiabilityOfBtc) {
		return true
	}

	return false
}

// SetTotalLiabilityOfBtc gets a reference to the given string and assigns it to the TotalLiabilityOfBtc field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetTotalLiabilityOfBtc(v string) {
	o.TotalLiabilityOfBtc = &v
}

// GetTotalNetAssetOfBtc returns the TotalNetAssetOfBtc field value if set, zero value otherwise.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetTotalNetAssetOfBtc() string {
	if o == nil || IsNil(o.TotalNetAssetOfBtc) {
		var ret string
		return ret
	}
	return *o.TotalNetAssetOfBtc
}

// GetTotalNetAssetOfBtcOk returns a tuple with the TotalNetAssetOfBtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) GetTotalNetAssetOfBtcOk() (*string, bool) {
	if o == nil || IsNil(o.TotalNetAssetOfBtc) {
		return nil, false
	}
	return o.TotalNetAssetOfBtc, true
}

// HasTotalNetAssetOfBtc returns a boolean if a field has been set.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) HasTotalNetAssetOfBtc() bool {
	if o != nil && !IsNil(o.TotalNetAssetOfBtc) {
		return true
	}

	return false
}

// SetTotalNetAssetOfBtc gets a reference to the given string and assigns it to the TotalNetAssetOfBtc field.
func (o *SubaccountGetSubAccountMarginAccountV1Resp) SetTotalNetAssetOfBtc(v string) {
	o.TotalNetAssetOfBtc = &v
}

func (o SubaccountGetSubAccountMarginAccountV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubaccountGetSubAccountMarginAccountV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.MarginLevel) {
		toSerialize["marginLevel"] = o.MarginLevel
	}
	if !IsNil(o.MarginTradeCoeffVo) {
		toSerialize["marginTradeCoeffVo"] = o.MarginTradeCoeffVo
	}
	if !IsNil(o.MarginUserAssetVoList) {
		toSerialize["marginUserAssetVoList"] = o.MarginUserAssetVoList
	}
	if !IsNil(o.TotalAssetOfBtc) {
		toSerialize["totalAssetOfBtc"] = o.TotalAssetOfBtc
	}
	if !IsNil(o.TotalLiabilityOfBtc) {
		toSerialize["totalLiabilityOfBtc"] = o.TotalLiabilityOfBtc
	}
	if !IsNil(o.TotalNetAssetOfBtc) {
		toSerialize["totalNetAssetOfBtc"] = o.TotalNetAssetOfBtc
	}
	return toSerialize, nil
}

type NullableSubaccountGetSubAccountMarginAccountV1Resp struct {
	value *SubaccountGetSubAccountMarginAccountV1Resp
	isSet bool
}

func (v NullableSubaccountGetSubAccountMarginAccountV1Resp) Get() *SubaccountGetSubAccountMarginAccountV1Resp {
	return v.value
}

func (v *NullableSubaccountGetSubAccountMarginAccountV1Resp) Set(val *SubaccountGetSubAccountMarginAccountV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableSubaccountGetSubAccountMarginAccountV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableSubaccountGetSubAccountMarginAccountV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubaccountGetSubAccountMarginAccountV1Resp(val *SubaccountGetSubAccountMarginAccountV1Resp) *NullableSubaccountGetSubAccountMarginAccountV1Resp {
	return &NullableSubaccountGetSubAccountMarginAccountV1Resp{value: val, isSet: true}
}

func (v NullableSubaccountGetSubAccountMarginAccountV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubaccountGetSubAccountMarginAccountV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


