/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the GetLoanFlexibleBorrowHistoryV2RespRowsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLoanFlexibleBorrowHistoryV2RespRowsInner{}

// GetLoanFlexibleBorrowHistoryV2RespRowsInner struct for GetLoanFlexibleBorrowHistoryV2RespRowsInner
type GetLoanFlexibleBorrowHistoryV2RespRowsInner struct {
	BorrowTime *int64 `json:"borrowTime,omitempty"`
	CollateralCoin *string `json:"collateralCoin,omitempty"`
	InitialCollateralAmount *string `json:"initialCollateralAmount,omitempty"`
	InitialLoanAmount *string `json:"initialLoanAmount,omitempty"`
	LoanCoin *string `json:"loanCoin,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewGetLoanFlexibleBorrowHistoryV2RespRowsInner instantiates a new GetLoanFlexibleBorrowHistoryV2RespRowsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLoanFlexibleBorrowHistoryV2RespRowsInner() *GetLoanFlexibleBorrowHistoryV2RespRowsInner {
	this := GetLoanFlexibleBorrowHistoryV2RespRowsInner{}
	return &this
}

// NewGetLoanFlexibleBorrowHistoryV2RespRowsInnerWithDefaults instantiates a new GetLoanFlexibleBorrowHistoryV2RespRowsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLoanFlexibleBorrowHistoryV2RespRowsInnerWithDefaults() *GetLoanFlexibleBorrowHistoryV2RespRowsInner {
	this := GetLoanFlexibleBorrowHistoryV2RespRowsInner{}
	return &this
}

// GetBorrowTime returns the BorrowTime field value if set, zero value otherwise.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetBorrowTime() int64 {
	if o == nil || IsNil(o.BorrowTime) {
		var ret int64
		return ret
	}
	return *o.BorrowTime
}

// GetBorrowTimeOk returns a tuple with the BorrowTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetBorrowTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.BorrowTime) {
		return nil, false
	}
	return o.BorrowTime, true
}

// HasBorrowTime returns a boolean if a field has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) HasBorrowTime() bool {
	if o != nil && !IsNil(o.BorrowTime) {
		return true
	}

	return false
}

// SetBorrowTime gets a reference to the given int64 and assigns it to the BorrowTime field.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) SetBorrowTime(v int64) {
	o.BorrowTime = &v
}

// GetCollateralCoin returns the CollateralCoin field value if set, zero value otherwise.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetCollateralCoin() string {
	if o == nil || IsNil(o.CollateralCoin) {
		var ret string
		return ret
	}
	return *o.CollateralCoin
}

// GetCollateralCoinOk returns a tuple with the CollateralCoin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetCollateralCoinOk() (*string, bool) {
	if o == nil || IsNil(o.CollateralCoin) {
		return nil, false
	}
	return o.CollateralCoin, true
}

// HasCollateralCoin returns a boolean if a field has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) HasCollateralCoin() bool {
	if o != nil && !IsNil(o.CollateralCoin) {
		return true
	}

	return false
}

// SetCollateralCoin gets a reference to the given string and assigns it to the CollateralCoin field.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) SetCollateralCoin(v string) {
	o.CollateralCoin = &v
}

// GetInitialCollateralAmount returns the InitialCollateralAmount field value if set, zero value otherwise.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetInitialCollateralAmount() string {
	if o == nil || IsNil(o.InitialCollateralAmount) {
		var ret string
		return ret
	}
	return *o.InitialCollateralAmount
}

// GetInitialCollateralAmountOk returns a tuple with the InitialCollateralAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetInitialCollateralAmountOk() (*string, bool) {
	if o == nil || IsNil(o.InitialCollateralAmount) {
		return nil, false
	}
	return o.InitialCollateralAmount, true
}

// HasInitialCollateralAmount returns a boolean if a field has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) HasInitialCollateralAmount() bool {
	if o != nil && !IsNil(o.InitialCollateralAmount) {
		return true
	}

	return false
}

// SetInitialCollateralAmount gets a reference to the given string and assigns it to the InitialCollateralAmount field.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) SetInitialCollateralAmount(v string) {
	o.InitialCollateralAmount = &v
}

// GetInitialLoanAmount returns the InitialLoanAmount field value if set, zero value otherwise.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetInitialLoanAmount() string {
	if o == nil || IsNil(o.InitialLoanAmount) {
		var ret string
		return ret
	}
	return *o.InitialLoanAmount
}

// GetInitialLoanAmountOk returns a tuple with the InitialLoanAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetInitialLoanAmountOk() (*string, bool) {
	if o == nil || IsNil(o.InitialLoanAmount) {
		return nil, false
	}
	return o.InitialLoanAmount, true
}

// HasInitialLoanAmount returns a boolean if a field has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) HasInitialLoanAmount() bool {
	if o != nil && !IsNil(o.InitialLoanAmount) {
		return true
	}

	return false
}

// SetInitialLoanAmount gets a reference to the given string and assigns it to the InitialLoanAmount field.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) SetInitialLoanAmount(v string) {
	o.InitialLoanAmount = &v
}

// GetLoanCoin returns the LoanCoin field value if set, zero value otherwise.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetLoanCoin() string {
	if o == nil || IsNil(o.LoanCoin) {
		var ret string
		return ret
	}
	return *o.LoanCoin
}

// GetLoanCoinOk returns a tuple with the LoanCoin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetLoanCoinOk() (*string, bool) {
	if o == nil || IsNil(o.LoanCoin) {
		return nil, false
	}
	return o.LoanCoin, true
}

// HasLoanCoin returns a boolean if a field has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) HasLoanCoin() bool {
	if o != nil && !IsNil(o.LoanCoin) {
		return true
	}

	return false
}

// SetLoanCoin gets a reference to the given string and assigns it to the LoanCoin field.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) SetLoanCoin(v string) {
	o.LoanCoin = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetLoanFlexibleBorrowHistoryV2RespRowsInner) SetStatus(v string) {
	o.Status = &v
}

func (o GetLoanFlexibleBorrowHistoryV2RespRowsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLoanFlexibleBorrowHistoryV2RespRowsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BorrowTime) {
		toSerialize["borrowTime"] = o.BorrowTime
	}
	if !IsNil(o.CollateralCoin) {
		toSerialize["collateralCoin"] = o.CollateralCoin
	}
	if !IsNil(o.InitialCollateralAmount) {
		toSerialize["initialCollateralAmount"] = o.InitialCollateralAmount
	}
	if !IsNil(o.InitialLoanAmount) {
		toSerialize["initialLoanAmount"] = o.InitialLoanAmount
	}
	if !IsNil(o.LoanCoin) {
		toSerialize["loanCoin"] = o.LoanCoin
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner struct {
	value *GetLoanFlexibleBorrowHistoryV2RespRowsInner
	isSet bool
}

func (v NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner) Get() *GetLoanFlexibleBorrowHistoryV2RespRowsInner {
	return v.value
}

func (v *NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner) Set(val *GetLoanFlexibleBorrowHistoryV2RespRowsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLoanFlexibleBorrowHistoryV2RespRowsInner(val *GetLoanFlexibleBorrowHistoryV2RespRowsInner) *NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner {
	return &NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner{value: val, isSet: true}
}

func (v NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLoanFlexibleBorrowHistoryV2RespRowsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


