/*
Binance Spot API

OpenAPI specification for Binance exchange - Spot API

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spot

import (
	"encoding/json"
)

// checks if the CreateApiReferralCustomizationV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApiReferralCustomizationV1Resp{}

// CreateApiReferralCustomizationV1Resp struct for CreateApiReferralCustomizationV1Resp
type CreateApiReferralCustomizationV1Resp struct {
	CustomerId *string `json:"customerId,omitempty"`
	Email *string `json:"email,omitempty"`
}

// NewCreateApiReferralCustomizationV1Resp instantiates a new CreateApiReferralCustomizationV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApiReferralCustomizationV1Resp() *CreateApiReferralCustomizationV1Resp {
	this := CreateApiReferralCustomizationV1Resp{}
	return &this
}

// NewCreateApiReferralCustomizationV1RespWithDefaults instantiates a new CreateApiReferralCustomizationV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApiReferralCustomizationV1RespWithDefaults() *CreateApiReferralCustomizationV1Resp {
	this := CreateApiReferralCustomizationV1Resp{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CreateApiReferralCustomizationV1Resp) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiReferralCustomizationV1Resp) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CreateApiReferralCustomizationV1Resp) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CreateApiReferralCustomizationV1Resp) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateApiReferralCustomizationV1Resp) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiReferralCustomizationV1Resp) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateApiReferralCustomizationV1Resp) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateApiReferralCustomizationV1Resp) SetEmail(v string) {
	o.Email = &v
}

func (o CreateApiReferralCustomizationV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApiReferralCustomizationV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableCreateApiReferralCustomizationV1Resp struct {
	value *CreateApiReferralCustomizationV1Resp
	isSet bool
}

func (v NullableCreateApiReferralCustomizationV1Resp) Get() *CreateApiReferralCustomizationV1Resp {
	return v.value
}

func (v *NullableCreateApiReferralCustomizationV1Resp) Set(val *CreateApiReferralCustomizationV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApiReferralCustomizationV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApiReferralCustomizationV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApiReferralCustomizationV1Resp(val *CreateApiReferralCustomizationV1Resp) *NullableCreateApiReferralCustomizationV1Resp {
	return &NullableCreateApiReferralCustomizationV1Resp{value: val, isSet: true}
}

func (v NullableCreateApiReferralCustomizationV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApiReferralCustomizationV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


