/*
Binance USD-M Futures API

OpenAPI specification for Binance exchange - Umfutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package umfutures

import (
	"encoding/json"
)

// checks if the GetIndexInfoV1RespItemBaseAssetListInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIndexInfoV1RespItemBaseAssetListInner{}

// GetIndexInfoV1RespItemBaseAssetListInner struct for GetIndexInfoV1RespItemBaseAssetListInner
type GetIndexInfoV1RespItemBaseAssetListInner struct {
	BaseAsset *string `json:"baseAsset,omitempty"`
	QuoteAsset *string `json:"quoteAsset,omitempty"`
	WeightInPercentage *string `json:"weightInPercentage,omitempty"`
	WeightInQuantity *string `json:"weightInQuantity,omitempty"`
}

// NewGetIndexInfoV1RespItemBaseAssetListInner instantiates a new GetIndexInfoV1RespItemBaseAssetListInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIndexInfoV1RespItemBaseAssetListInner() *GetIndexInfoV1RespItemBaseAssetListInner {
	this := GetIndexInfoV1RespItemBaseAssetListInner{}
	return &this
}

// NewGetIndexInfoV1RespItemBaseAssetListInnerWithDefaults instantiates a new GetIndexInfoV1RespItemBaseAssetListInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIndexInfoV1RespItemBaseAssetListInnerWithDefaults() *GetIndexInfoV1RespItemBaseAssetListInner {
	this := GetIndexInfoV1RespItemBaseAssetListInner{}
	return &this
}

// GetBaseAsset returns the BaseAsset field value if set, zero value otherwise.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetBaseAsset() string {
	if o == nil || IsNil(o.BaseAsset) {
		var ret string
		return ret
	}
	return *o.BaseAsset
}

// GetBaseAssetOk returns a tuple with the BaseAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetBaseAssetOk() (*string, bool) {
	if o == nil || IsNil(o.BaseAsset) {
		return nil, false
	}
	return o.BaseAsset, true
}

// HasBaseAsset returns a boolean if a field has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) HasBaseAsset() bool {
	if o != nil && !IsNil(o.BaseAsset) {
		return true
	}

	return false
}

// SetBaseAsset gets a reference to the given string and assigns it to the BaseAsset field.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) SetBaseAsset(v string) {
	o.BaseAsset = &v
}

// GetQuoteAsset returns the QuoteAsset field value if set, zero value otherwise.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetQuoteAsset() string {
	if o == nil || IsNil(o.QuoteAsset) {
		var ret string
		return ret
	}
	return *o.QuoteAsset
}

// GetQuoteAssetOk returns a tuple with the QuoteAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetQuoteAssetOk() (*string, bool) {
	if o == nil || IsNil(o.QuoteAsset) {
		return nil, false
	}
	return o.QuoteAsset, true
}

// HasQuoteAsset returns a boolean if a field has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) HasQuoteAsset() bool {
	if o != nil && !IsNil(o.QuoteAsset) {
		return true
	}

	return false
}

// SetQuoteAsset gets a reference to the given string and assigns it to the QuoteAsset field.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) SetQuoteAsset(v string) {
	o.QuoteAsset = &v
}

// GetWeightInPercentage returns the WeightInPercentage field value if set, zero value otherwise.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetWeightInPercentage() string {
	if o == nil || IsNil(o.WeightInPercentage) {
		var ret string
		return ret
	}
	return *o.WeightInPercentage
}

// GetWeightInPercentageOk returns a tuple with the WeightInPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetWeightInPercentageOk() (*string, bool) {
	if o == nil || IsNil(o.WeightInPercentage) {
		return nil, false
	}
	return o.WeightInPercentage, true
}

// HasWeightInPercentage returns a boolean if a field has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) HasWeightInPercentage() bool {
	if o != nil && !IsNil(o.WeightInPercentage) {
		return true
	}

	return false
}

// SetWeightInPercentage gets a reference to the given string and assigns it to the WeightInPercentage field.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) SetWeightInPercentage(v string) {
	o.WeightInPercentage = &v
}

// GetWeightInQuantity returns the WeightInQuantity field value if set, zero value otherwise.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetWeightInQuantity() string {
	if o == nil || IsNil(o.WeightInQuantity) {
		var ret string
		return ret
	}
	return *o.WeightInQuantity
}

// GetWeightInQuantityOk returns a tuple with the WeightInQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) GetWeightInQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.WeightInQuantity) {
		return nil, false
	}
	return o.WeightInQuantity, true
}

// HasWeightInQuantity returns a boolean if a field has been set.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) HasWeightInQuantity() bool {
	if o != nil && !IsNil(o.WeightInQuantity) {
		return true
	}

	return false
}

// SetWeightInQuantity gets a reference to the given string and assigns it to the WeightInQuantity field.
func (o *GetIndexInfoV1RespItemBaseAssetListInner) SetWeightInQuantity(v string) {
	o.WeightInQuantity = &v
}

func (o GetIndexInfoV1RespItemBaseAssetListInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIndexInfoV1RespItemBaseAssetListInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BaseAsset) {
		toSerialize["baseAsset"] = o.BaseAsset
	}
	if !IsNil(o.QuoteAsset) {
		toSerialize["quoteAsset"] = o.QuoteAsset
	}
	if !IsNil(o.WeightInPercentage) {
		toSerialize["weightInPercentage"] = o.WeightInPercentage
	}
	if !IsNil(o.WeightInQuantity) {
		toSerialize["weightInQuantity"] = o.WeightInQuantity
	}
	return toSerialize, nil
}

type NullableGetIndexInfoV1RespItemBaseAssetListInner struct {
	value *GetIndexInfoV1RespItemBaseAssetListInner
	isSet bool
}

func (v NullableGetIndexInfoV1RespItemBaseAssetListInner) Get() *GetIndexInfoV1RespItemBaseAssetListInner {
	return v.value
}

func (v *NullableGetIndexInfoV1RespItemBaseAssetListInner) Set(val *GetIndexInfoV1RespItemBaseAssetListInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIndexInfoV1RespItemBaseAssetListInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIndexInfoV1RespItemBaseAssetListInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIndexInfoV1RespItemBaseAssetListInner(val *GetIndexInfoV1RespItemBaseAssetListInner) *NullableGetIndexInfoV1RespItemBaseAssetListInner {
	return &NullableGetIndexInfoV1RespItemBaseAssetListInner{value: val, isSet: true}
}

func (v NullableGetIndexInfoV1RespItemBaseAssetListInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIndexInfoV1RespItemBaseAssetListInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


