/*
Binance Ufutures API

OpenAPI specification for Binance cryptocurrency exchange - Ufutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ufutures

import (
	"encoding/json"
)

// checks if the UfuturesGetApiTradingStatusV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UfuturesGetApiTradingStatusV1Resp{}

// UfuturesGetApiTradingStatusV1Resp struct for UfuturesGetApiTradingStatusV1Resp
type UfuturesGetApiTradingStatusV1Resp struct {
	Indicators map[string]interface{} `json:"indicators,omitempty"`
	UpdateTime *int64 `json:"updateTime,omitempty"`
}

// NewUfuturesGetApiTradingStatusV1Resp instantiates a new UfuturesGetApiTradingStatusV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUfuturesGetApiTradingStatusV1Resp() *UfuturesGetApiTradingStatusV1Resp {
	this := UfuturesGetApiTradingStatusV1Resp{}
	return &this
}

// NewUfuturesGetApiTradingStatusV1RespWithDefaults instantiates a new UfuturesGetApiTradingStatusV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUfuturesGetApiTradingStatusV1RespWithDefaults() *UfuturesGetApiTradingStatusV1Resp {
	this := UfuturesGetApiTradingStatusV1Resp{}
	return &this
}

// GetIndicators returns the Indicators field value if set, zero value otherwise.
func (o *UfuturesGetApiTradingStatusV1Resp) GetIndicators() map[string]interface{} {
	if o == nil || IsNil(o.Indicators) {
		var ret map[string]interface{}
		return ret
	}
	return o.Indicators
}

// GetIndicatorsOk returns a tuple with the Indicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UfuturesGetApiTradingStatusV1Resp) GetIndicatorsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Indicators) {
		return map[string]interface{}{}, false
	}
	return o.Indicators, true
}

// HasIndicators returns a boolean if a field has been set.
func (o *UfuturesGetApiTradingStatusV1Resp) HasIndicators() bool {
	if o != nil && !IsNil(o.Indicators) {
		return true
	}

	return false
}

// SetIndicators gets a reference to the given map[string]interface{} and assigns it to the Indicators field.
func (o *UfuturesGetApiTradingStatusV1Resp) SetIndicators(v map[string]interface{}) {
	o.Indicators = v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *UfuturesGetApiTradingStatusV1Resp) GetUpdateTime() int64 {
	if o == nil || IsNil(o.UpdateTime) {
		var ret int64
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UfuturesGetApiTradingStatusV1Resp) GetUpdateTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *UfuturesGetApiTradingStatusV1Resp) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given int64 and assigns it to the UpdateTime field.
func (o *UfuturesGetApiTradingStatusV1Resp) SetUpdateTime(v int64) {
	o.UpdateTime = &v
}

func (o UfuturesGetApiTradingStatusV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UfuturesGetApiTradingStatusV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Indicators) {
		toSerialize["indicators"] = o.Indicators
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["updateTime"] = o.UpdateTime
	}
	return toSerialize, nil
}

type NullableUfuturesGetApiTradingStatusV1Resp struct {
	value *UfuturesGetApiTradingStatusV1Resp
	isSet bool
}

func (v NullableUfuturesGetApiTradingStatusV1Resp) Get() *UfuturesGetApiTradingStatusV1Resp {
	return v.value
}

func (v *NullableUfuturesGetApiTradingStatusV1Resp) Set(val *UfuturesGetApiTradingStatusV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableUfuturesGetApiTradingStatusV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableUfuturesGetApiTradingStatusV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUfuturesGetApiTradingStatusV1Resp(val *UfuturesGetApiTradingStatusV1Resp) *NullableUfuturesGetApiTradingStatusV1Resp {
	return &NullableUfuturesGetApiTradingStatusV1Resp{value: val, isSet: true}
}

func (v NullableUfuturesGetApiTradingStatusV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUfuturesGetApiTradingStatusV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


