/*
Binance Cmfutures API

OpenAPI specification for Binance cryptocurrency exchange - Cmfutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cmfutures

import (
	"encoding/json"
)

// checks if the CmfuturesGetLeverageBracketV2RespItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CmfuturesGetLeverageBracketV2RespItem{}

// CmfuturesGetLeverageBracketV2RespItem struct for CmfuturesGetLeverageBracketV2RespItem
type CmfuturesGetLeverageBracketV2RespItem struct {
	Brackets []CmfuturesGetLeverageBracketV1RespItemBracketsInner `json:"brackets,omitempty"`
	NotionalCoef *float32 `json:"notionalCoef,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
}

// NewCmfuturesGetLeverageBracketV2RespItem instantiates a new CmfuturesGetLeverageBracketV2RespItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCmfuturesGetLeverageBracketV2RespItem() *CmfuturesGetLeverageBracketV2RespItem {
	this := CmfuturesGetLeverageBracketV2RespItem{}
	return &this
}

// NewCmfuturesGetLeverageBracketV2RespItemWithDefaults instantiates a new CmfuturesGetLeverageBracketV2RespItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCmfuturesGetLeverageBracketV2RespItemWithDefaults() *CmfuturesGetLeverageBracketV2RespItem {
	this := CmfuturesGetLeverageBracketV2RespItem{}
	return &this
}

// GetBrackets returns the Brackets field value if set, zero value otherwise.
func (o *CmfuturesGetLeverageBracketV2RespItem) GetBrackets() []CmfuturesGetLeverageBracketV1RespItemBracketsInner {
	if o == nil || IsNil(o.Brackets) {
		var ret []CmfuturesGetLeverageBracketV1RespItemBracketsInner
		return ret
	}
	return o.Brackets
}

// GetBracketsOk returns a tuple with the Brackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CmfuturesGetLeverageBracketV2RespItem) GetBracketsOk() ([]CmfuturesGetLeverageBracketV1RespItemBracketsInner, bool) {
	if o == nil || IsNil(o.Brackets) {
		return nil, false
	}
	return o.Brackets, true
}

// HasBrackets returns a boolean if a field has been set.
func (o *CmfuturesGetLeverageBracketV2RespItem) HasBrackets() bool {
	if o != nil && !IsNil(o.Brackets) {
		return true
	}

	return false
}

// SetBrackets gets a reference to the given []CmfuturesGetLeverageBracketV1RespItemBracketsInner and assigns it to the Brackets field.
func (o *CmfuturesGetLeverageBracketV2RespItem) SetBrackets(v []CmfuturesGetLeverageBracketV1RespItemBracketsInner) {
	o.Brackets = v
}

// GetNotionalCoef returns the NotionalCoef field value if set, zero value otherwise.
func (o *CmfuturesGetLeverageBracketV2RespItem) GetNotionalCoef() float32 {
	if o == nil || IsNil(o.NotionalCoef) {
		var ret float32
		return ret
	}
	return *o.NotionalCoef
}

// GetNotionalCoefOk returns a tuple with the NotionalCoef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CmfuturesGetLeverageBracketV2RespItem) GetNotionalCoefOk() (*float32, bool) {
	if o == nil || IsNil(o.NotionalCoef) {
		return nil, false
	}
	return o.NotionalCoef, true
}

// HasNotionalCoef returns a boolean if a field has been set.
func (o *CmfuturesGetLeverageBracketV2RespItem) HasNotionalCoef() bool {
	if o != nil && !IsNil(o.NotionalCoef) {
		return true
	}

	return false
}

// SetNotionalCoef gets a reference to the given float32 and assigns it to the NotionalCoef field.
func (o *CmfuturesGetLeverageBracketV2RespItem) SetNotionalCoef(v float32) {
	o.NotionalCoef = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *CmfuturesGetLeverageBracketV2RespItem) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CmfuturesGetLeverageBracketV2RespItem) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *CmfuturesGetLeverageBracketV2RespItem) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *CmfuturesGetLeverageBracketV2RespItem) SetSymbol(v string) {
	o.Symbol = &v
}

func (o CmfuturesGetLeverageBracketV2RespItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CmfuturesGetLeverageBracketV2RespItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brackets) {
		toSerialize["brackets"] = o.Brackets
	}
	if !IsNil(o.NotionalCoef) {
		toSerialize["notionalCoef"] = o.NotionalCoef
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	return toSerialize, nil
}

type NullableCmfuturesGetLeverageBracketV2RespItem struct {
	value *CmfuturesGetLeverageBracketV2RespItem
	isSet bool
}

func (v NullableCmfuturesGetLeverageBracketV2RespItem) Get() *CmfuturesGetLeverageBracketV2RespItem {
	return v.value
}

func (v *NullableCmfuturesGetLeverageBracketV2RespItem) Set(val *CmfuturesGetLeverageBracketV2RespItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCmfuturesGetLeverageBracketV2RespItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCmfuturesGetLeverageBracketV2RespItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCmfuturesGetLeverageBracketV2RespItem(val *CmfuturesGetLeverageBracketV2RespItem) *NullableCmfuturesGetLeverageBracketV2RespItem {
	return &NullableCmfuturesGetLeverageBracketV2RespItem{value: val, isSet: true}
}

func (v NullableCmfuturesGetLeverageBracketV2RespItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCmfuturesGetLeverageBracketV2RespItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


