/*
Binance Cfutures API

OpenAPI specification for Binance cryptocurrency exchange - Cfutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cmfutures

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CfuturesUpdateBatchOrdersV1RespInner - struct for CfuturesUpdateBatchOrdersV1RespInner
type CfuturesUpdateBatchOrdersV1RespInner struct {
	APIError *APIError
	CfuturesUpdateBatchOrdersV1RespItem *CfuturesUpdateBatchOrdersV1RespItem
}

// APIErrorAsCfuturesUpdateBatchOrdersV1RespInner is a convenience function that returns APIError wrapped in CfuturesUpdateBatchOrdersV1RespInner
func APIErrorAsCfuturesUpdateBatchOrdersV1RespInner(v *APIError) CfuturesUpdateBatchOrdersV1RespInner {
	return CfuturesUpdateBatchOrdersV1RespInner{
		APIError: v,
	}
}

// CfuturesUpdateBatchOrdersV1RespItemAsCfuturesUpdateBatchOrdersV1RespInner is a convenience function that returns CfuturesUpdateBatchOrdersV1RespItem wrapped in CfuturesUpdateBatchOrdersV1RespInner
func CfuturesUpdateBatchOrdersV1RespItemAsCfuturesUpdateBatchOrdersV1RespInner(v *CfuturesUpdateBatchOrdersV1RespItem) CfuturesUpdateBatchOrdersV1RespInner {
	return CfuturesUpdateBatchOrdersV1RespInner{
		CfuturesUpdateBatchOrdersV1RespItem: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CfuturesUpdateBatchOrdersV1RespInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into APIError
	err = newStrictDecoder(data).Decode(&dst.APIError)
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			if err = validator.Validate(dst.APIError); err != nil {
				dst.APIError = nil
			} else {
				match++
			}
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal data into CfuturesUpdateBatchOrdersV1RespItem
	err = newStrictDecoder(data).Decode(&dst.CfuturesUpdateBatchOrdersV1RespItem)
	if err == nil {
		jsonCfuturesUpdateBatchOrdersV1RespItem, _ := json.Marshal(dst.CfuturesUpdateBatchOrdersV1RespItem)
		if string(jsonCfuturesUpdateBatchOrdersV1RespItem) == "{}" { // empty struct
			dst.CfuturesUpdateBatchOrdersV1RespItem = nil
		} else {
			if err = validator.Validate(dst.CfuturesUpdateBatchOrdersV1RespItem); err != nil {
				dst.CfuturesUpdateBatchOrdersV1RespItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.CfuturesUpdateBatchOrdersV1RespItem = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.APIError = nil
		dst.CfuturesUpdateBatchOrdersV1RespItem = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CfuturesUpdateBatchOrdersV1RespInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CfuturesUpdateBatchOrdersV1RespInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CfuturesUpdateBatchOrdersV1RespInner) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.CfuturesUpdateBatchOrdersV1RespItem != nil {
		return json.Marshal(&src.CfuturesUpdateBatchOrdersV1RespItem)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CfuturesUpdateBatchOrdersV1RespInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.APIError != nil {
		return obj.APIError
	}

	if obj.CfuturesUpdateBatchOrdersV1RespItem != nil {
		return obj.CfuturesUpdateBatchOrdersV1RespItem
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CfuturesUpdateBatchOrdersV1RespInner) GetActualInstanceValue() (interface{}) {
	if obj.APIError != nil {
		return *obj.APIError
	}

	if obj.CfuturesUpdateBatchOrdersV1RespItem != nil {
		return *obj.CfuturesUpdateBatchOrdersV1RespItem
	}

	// all schemas are nil
	return nil
}

type NullableCfuturesUpdateBatchOrdersV1RespInner struct {
	value *CfuturesUpdateBatchOrdersV1RespInner
	isSet bool
}

func (v NullableCfuturesUpdateBatchOrdersV1RespInner) Get() *CfuturesUpdateBatchOrdersV1RespInner {
	return v.value
}

func (v *NullableCfuturesUpdateBatchOrdersV1RespInner) Set(val *CfuturesUpdateBatchOrdersV1RespInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCfuturesUpdateBatchOrdersV1RespInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCfuturesUpdateBatchOrdersV1RespInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCfuturesUpdateBatchOrdersV1RespInner(val *CfuturesUpdateBatchOrdersV1RespInner) *NullableCfuturesUpdateBatchOrdersV1RespInner {
	return &NullableCfuturesUpdateBatchOrdersV1RespInner{value: val, isSet: true}
}

func (v NullableCfuturesUpdateBatchOrdersV1RespInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCfuturesUpdateBatchOrdersV1RespInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


