/*
Binance Cfutures API

OpenAPI specification for Binance cryptocurrency exchange - Cfutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cmfutures

import (
	"encoding/json"
)

// checks if the CfuturesCreateListenKeyV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CfuturesCreateListenKeyV1Resp{}

// CfuturesCreateListenKeyV1Resp struct for CfuturesCreateListenKeyV1Resp
type CfuturesCreateListenKeyV1Resp struct {
	ListenKey *string `json:"listenKey,omitempty"`
}

// NewCfuturesCreateListenKeyV1Resp instantiates a new CfuturesCreateListenKeyV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCfuturesCreateListenKeyV1Resp() *CfuturesCreateListenKeyV1Resp {
	this := CfuturesCreateListenKeyV1Resp{}
	return &this
}

// NewCfuturesCreateListenKeyV1RespWithDefaults instantiates a new CfuturesCreateListenKeyV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCfuturesCreateListenKeyV1RespWithDefaults() *CfuturesCreateListenKeyV1Resp {
	this := CfuturesCreateListenKeyV1Resp{}
	return &this
}

// GetListenKey returns the ListenKey field value if set, zero value otherwise.
func (o *CfuturesCreateListenKeyV1Resp) GetListenKey() string {
	if o == nil || IsNil(o.ListenKey) {
		var ret string
		return ret
	}
	return *o.ListenKey
}

// GetListenKeyOk returns a tuple with the ListenKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CfuturesCreateListenKeyV1Resp) GetListenKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ListenKey) {
		return nil, false
	}
	return o.ListenKey, true
}

// HasListenKey returns a boolean if a field has been set.
func (o *CfuturesCreateListenKeyV1Resp) HasListenKey() bool {
	if o != nil && !IsNil(o.ListenKey) {
		return true
	}

	return false
}

// SetListenKey gets a reference to the given string and assigns it to the ListenKey field.
func (o *CfuturesCreateListenKeyV1Resp) SetListenKey(v string) {
	o.ListenKey = &v
}

func (o CfuturesCreateListenKeyV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CfuturesCreateListenKeyV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ListenKey) {
		toSerialize["listenKey"] = o.ListenKey
	}
	return toSerialize, nil
}

type NullableCfuturesCreateListenKeyV1Resp struct {
	value *CfuturesCreateListenKeyV1Resp
	isSet bool
}

func (v NullableCfuturesCreateListenKeyV1Resp) Get() *CfuturesCreateListenKeyV1Resp {
	return v.value
}

func (v *NullableCfuturesCreateListenKeyV1Resp) Set(val *CfuturesCreateListenKeyV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableCfuturesCreateListenKeyV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableCfuturesCreateListenKeyV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCfuturesCreateListenKeyV1Resp(val *CfuturesCreateListenKeyV1Resp) *NullableCfuturesCreateListenKeyV1Resp {
	return &NullableCfuturesCreateListenKeyV1Resp{value: val, isSet: true}
}

func (v NullableCfuturesCreateListenKeyV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCfuturesCreateListenKeyV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


