/*
Binance Portfolio Margin API

OpenAPI specification for Binance exchange - Pmargin API

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmargin

import (
	"encoding/json"
)

// checks if the GetCmOrderAmendmentV1RespItemAmendment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCmOrderAmendmentV1RespItemAmendment{}

// GetCmOrderAmendmentV1RespItemAmendment struct for GetCmOrderAmendmentV1RespItemAmendment
type GetCmOrderAmendmentV1RespItemAmendment struct {
	Count *int32 `json:"count,omitempty"`
	OrigQty *GetCmOrderAmendmentV1RespItemAmendmentOrigQty `json:"origQty,omitempty"`
	Price *GetCmOrderAmendmentV1RespItemAmendmentOrigQty `json:"price,omitempty"`
}

// NewGetCmOrderAmendmentV1RespItemAmendment instantiates a new GetCmOrderAmendmentV1RespItemAmendment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCmOrderAmendmentV1RespItemAmendment() *GetCmOrderAmendmentV1RespItemAmendment {
	this := GetCmOrderAmendmentV1RespItemAmendment{}
	return &this
}

// NewGetCmOrderAmendmentV1RespItemAmendmentWithDefaults instantiates a new GetCmOrderAmendmentV1RespItemAmendment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCmOrderAmendmentV1RespItemAmendmentWithDefaults() *GetCmOrderAmendmentV1RespItemAmendment {
	this := GetCmOrderAmendmentV1RespItemAmendment{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetCmOrderAmendmentV1RespItemAmendment) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCmOrderAmendmentV1RespItemAmendment) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetCmOrderAmendmentV1RespItemAmendment) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetCmOrderAmendmentV1RespItemAmendment) SetCount(v int32) {
	o.Count = &v
}

// GetOrigQty returns the OrigQty field value if set, zero value otherwise.
func (o *GetCmOrderAmendmentV1RespItemAmendment) GetOrigQty() GetCmOrderAmendmentV1RespItemAmendmentOrigQty {
	if o == nil || IsNil(o.OrigQty) {
		var ret GetCmOrderAmendmentV1RespItemAmendmentOrigQty
		return ret
	}
	return *o.OrigQty
}

// GetOrigQtyOk returns a tuple with the OrigQty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCmOrderAmendmentV1RespItemAmendment) GetOrigQtyOk() (*GetCmOrderAmendmentV1RespItemAmendmentOrigQty, bool) {
	if o == nil || IsNil(o.OrigQty) {
		return nil, false
	}
	return o.OrigQty, true
}

// HasOrigQty returns a boolean if a field has been set.
func (o *GetCmOrderAmendmentV1RespItemAmendment) HasOrigQty() bool {
	if o != nil && !IsNil(o.OrigQty) {
		return true
	}

	return false
}

// SetOrigQty gets a reference to the given GetCmOrderAmendmentV1RespItemAmendmentOrigQty and assigns it to the OrigQty field.
func (o *GetCmOrderAmendmentV1RespItemAmendment) SetOrigQty(v GetCmOrderAmendmentV1RespItemAmendmentOrigQty) {
	o.OrigQty = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GetCmOrderAmendmentV1RespItemAmendment) GetPrice() GetCmOrderAmendmentV1RespItemAmendmentOrigQty {
	if o == nil || IsNil(o.Price) {
		var ret GetCmOrderAmendmentV1RespItemAmendmentOrigQty
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCmOrderAmendmentV1RespItemAmendment) GetPriceOk() (*GetCmOrderAmendmentV1RespItemAmendmentOrigQty, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GetCmOrderAmendmentV1RespItemAmendment) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given GetCmOrderAmendmentV1RespItemAmendmentOrigQty and assigns it to the Price field.
func (o *GetCmOrderAmendmentV1RespItemAmendment) SetPrice(v GetCmOrderAmendmentV1RespItemAmendmentOrigQty) {
	o.Price = &v
}

func (o GetCmOrderAmendmentV1RespItemAmendment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCmOrderAmendmentV1RespItemAmendment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.OrigQty) {
		toSerialize["origQty"] = o.OrigQty
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableGetCmOrderAmendmentV1RespItemAmendment struct {
	value *GetCmOrderAmendmentV1RespItemAmendment
	isSet bool
}

func (v NullableGetCmOrderAmendmentV1RespItemAmendment) Get() *GetCmOrderAmendmentV1RespItemAmendment {
	return v.value
}

func (v *NullableGetCmOrderAmendmentV1RespItemAmendment) Set(val *GetCmOrderAmendmentV1RespItemAmendment) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCmOrderAmendmentV1RespItemAmendment) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCmOrderAmendmentV1RespItemAmendment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCmOrderAmendmentV1RespItemAmendment(val *GetCmOrderAmendmentV1RespItemAmendment) *NullableGetCmOrderAmendmentV1RespItemAmendment {
	return &NullableGetCmOrderAmendmentV1RespItemAmendment{value: val, isSet: true}
}

func (v NullableGetCmOrderAmendmentV1RespItemAmendment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCmOrderAmendmentV1RespItemAmendment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


