/*
Binance USD-M Futures API

OpenAPI specification for Binance exchange - Umfutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package umfutures

import (
	"encoding/json"
)

// checks if the UmfuturesCreateConvertAcceptQuoteV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UmfuturesCreateConvertAcceptQuoteV1Resp{}

// UmfuturesCreateConvertAcceptQuoteV1Resp struct for UmfuturesCreateConvertAcceptQuoteV1Resp
type UmfuturesCreateConvertAcceptQuoteV1Resp struct {
	CreateTime *int64 `json:"createTime,omitempty"`
	OrderId *string `json:"orderId,omitempty"`
	OrderStatus *string `json:"orderStatus,omitempty"`
}

// NewUmfuturesCreateConvertAcceptQuoteV1Resp instantiates a new UmfuturesCreateConvertAcceptQuoteV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUmfuturesCreateConvertAcceptQuoteV1Resp() *UmfuturesCreateConvertAcceptQuoteV1Resp {
	this := UmfuturesCreateConvertAcceptQuoteV1Resp{}
	return &this
}

// NewUmfuturesCreateConvertAcceptQuoteV1RespWithDefaults instantiates a new UmfuturesCreateConvertAcceptQuoteV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUmfuturesCreateConvertAcceptQuoteV1RespWithDefaults() *UmfuturesCreateConvertAcceptQuoteV1Resp {
	this := UmfuturesCreateConvertAcceptQuoteV1Resp{}
	return &this
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) GetCreateTime() int64 {
	if o == nil || IsNil(o.CreateTime) {
		var ret int64
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) GetCreateTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given int64 and assigns it to the CreateTime field.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) SetCreateTime(v int64) {
	o.CreateTime = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) SetOrderId(v string) {
	o.OrderId = &v
}

// GetOrderStatus returns the OrderStatus field value if set, zero value otherwise.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) GetOrderStatus() string {
	if o == nil || IsNil(o.OrderStatus) {
		var ret string
		return ret
	}
	return *o.OrderStatus
}

// GetOrderStatusOk returns a tuple with the OrderStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) GetOrderStatusOk() (*string, bool) {
	if o == nil || IsNil(o.OrderStatus) {
		return nil, false
	}
	return o.OrderStatus, true
}

// HasOrderStatus returns a boolean if a field has been set.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) HasOrderStatus() bool {
	if o != nil && !IsNil(o.OrderStatus) {
		return true
	}

	return false
}

// SetOrderStatus gets a reference to the given string and assigns it to the OrderStatus field.
func (o *UmfuturesCreateConvertAcceptQuoteV1Resp) SetOrderStatus(v string) {
	o.OrderStatus = &v
}

func (o UmfuturesCreateConvertAcceptQuoteV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UmfuturesCreateConvertAcceptQuoteV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.OrderStatus) {
		toSerialize["orderStatus"] = o.OrderStatus
	}
	return toSerialize, nil
}

type NullableUmfuturesCreateConvertAcceptQuoteV1Resp struct {
	value *UmfuturesCreateConvertAcceptQuoteV1Resp
	isSet bool
}

func (v NullableUmfuturesCreateConvertAcceptQuoteV1Resp) Get() *UmfuturesCreateConvertAcceptQuoteV1Resp {
	return v.value
}

func (v *NullableUmfuturesCreateConvertAcceptQuoteV1Resp) Set(val *UmfuturesCreateConvertAcceptQuoteV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableUmfuturesCreateConvertAcceptQuoteV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableUmfuturesCreateConvertAcceptQuoteV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUmfuturesCreateConvertAcceptQuoteV1Resp(val *UmfuturesCreateConvertAcceptQuoteV1Resp) *NullableUmfuturesCreateConvertAcceptQuoteV1Resp {
	return &NullableUmfuturesCreateConvertAcceptQuoteV1Resp{value: val, isSet: true}
}

func (v NullableUmfuturesCreateConvertAcceptQuoteV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUmfuturesCreateConvertAcceptQuoteV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


