/*
Binance USD-M Futures API

OpenAPI specification for Binance exchange - Umfutures API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package umfutures

import (
	"encoding/json"
)

// checks if the UmfuturesGetConvertOrderStatusV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UmfuturesGetConvertOrderStatusV1Resp{}

// UmfuturesGetConvertOrderStatusV1Resp struct for UmfuturesGetConvertOrderStatusV1Resp
type UmfuturesGetConvertOrderStatusV1Resp struct {
	CreateTime *int64 `json:"createTime,omitempty"`
	FromAmount *string `json:"fromAmount,omitempty"`
	FromAsset *string `json:"fromAsset,omitempty"`
	InverseRatio *string `json:"inverseRatio,omitempty"`
	OrderId *int64 `json:"orderId,omitempty"`
	OrderStatus *string `json:"orderStatus,omitempty"`
	Ratio *string `json:"ratio,omitempty"`
	ToAmount *string `json:"toAmount,omitempty"`
	ToAsset *string `json:"toAsset,omitempty"`
}

// NewUmfuturesGetConvertOrderStatusV1Resp instantiates a new UmfuturesGetConvertOrderStatusV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUmfuturesGetConvertOrderStatusV1Resp() *UmfuturesGetConvertOrderStatusV1Resp {
	this := UmfuturesGetConvertOrderStatusV1Resp{}
	return &this
}

// NewUmfuturesGetConvertOrderStatusV1RespWithDefaults instantiates a new UmfuturesGetConvertOrderStatusV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUmfuturesGetConvertOrderStatusV1RespWithDefaults() *UmfuturesGetConvertOrderStatusV1Resp {
	this := UmfuturesGetConvertOrderStatusV1Resp{}
	return &this
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetCreateTime() int64 {
	if o == nil || IsNil(o.CreateTime) {
		var ret int64
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetCreateTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given int64 and assigns it to the CreateTime field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetCreateTime(v int64) {
	o.CreateTime = &v
}

// GetFromAmount returns the FromAmount field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetFromAmount() string {
	if o == nil || IsNil(o.FromAmount) {
		var ret string
		return ret
	}
	return *o.FromAmount
}

// GetFromAmountOk returns a tuple with the FromAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetFromAmountOk() (*string, bool) {
	if o == nil || IsNil(o.FromAmount) {
		return nil, false
	}
	return o.FromAmount, true
}

// HasFromAmount returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasFromAmount() bool {
	if o != nil && !IsNil(o.FromAmount) {
		return true
	}

	return false
}

// SetFromAmount gets a reference to the given string and assigns it to the FromAmount field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetFromAmount(v string) {
	o.FromAmount = &v
}

// GetFromAsset returns the FromAsset field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetFromAsset() string {
	if o == nil || IsNil(o.FromAsset) {
		var ret string
		return ret
	}
	return *o.FromAsset
}

// GetFromAssetOk returns a tuple with the FromAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetFromAssetOk() (*string, bool) {
	if o == nil || IsNil(o.FromAsset) {
		return nil, false
	}
	return o.FromAsset, true
}

// HasFromAsset returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasFromAsset() bool {
	if o != nil && !IsNil(o.FromAsset) {
		return true
	}

	return false
}

// SetFromAsset gets a reference to the given string and assigns it to the FromAsset field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetFromAsset(v string) {
	o.FromAsset = &v
}

// GetInverseRatio returns the InverseRatio field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetInverseRatio() string {
	if o == nil || IsNil(o.InverseRatio) {
		var ret string
		return ret
	}
	return *o.InverseRatio
}

// GetInverseRatioOk returns a tuple with the InverseRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetInverseRatioOk() (*string, bool) {
	if o == nil || IsNil(o.InverseRatio) {
		return nil, false
	}
	return o.InverseRatio, true
}

// HasInverseRatio returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasInverseRatio() bool {
	if o != nil && !IsNil(o.InverseRatio) {
		return true
	}

	return false
}

// SetInverseRatio gets a reference to the given string and assigns it to the InverseRatio field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetInverseRatio(v string) {
	o.InverseRatio = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetOrderId() int64 {
	if o == nil || IsNil(o.OrderId) {
		var ret int64
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetOrderIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int64 and assigns it to the OrderId field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetOrderId(v int64) {
	o.OrderId = &v
}

// GetOrderStatus returns the OrderStatus field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetOrderStatus() string {
	if o == nil || IsNil(o.OrderStatus) {
		var ret string
		return ret
	}
	return *o.OrderStatus
}

// GetOrderStatusOk returns a tuple with the OrderStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetOrderStatusOk() (*string, bool) {
	if o == nil || IsNil(o.OrderStatus) {
		return nil, false
	}
	return o.OrderStatus, true
}

// HasOrderStatus returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasOrderStatus() bool {
	if o != nil && !IsNil(o.OrderStatus) {
		return true
	}

	return false
}

// SetOrderStatus gets a reference to the given string and assigns it to the OrderStatus field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetOrderStatus(v string) {
	o.OrderStatus = &v
}

// GetRatio returns the Ratio field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetRatio() string {
	if o == nil || IsNil(o.Ratio) {
		var ret string
		return ret
	}
	return *o.Ratio
}

// GetRatioOk returns a tuple with the Ratio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetRatioOk() (*string, bool) {
	if o == nil || IsNil(o.Ratio) {
		return nil, false
	}
	return o.Ratio, true
}

// HasRatio returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasRatio() bool {
	if o != nil && !IsNil(o.Ratio) {
		return true
	}

	return false
}

// SetRatio gets a reference to the given string and assigns it to the Ratio field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetRatio(v string) {
	o.Ratio = &v
}

// GetToAmount returns the ToAmount field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetToAmount() string {
	if o == nil || IsNil(o.ToAmount) {
		var ret string
		return ret
	}
	return *o.ToAmount
}

// GetToAmountOk returns a tuple with the ToAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetToAmountOk() (*string, bool) {
	if o == nil || IsNil(o.ToAmount) {
		return nil, false
	}
	return o.ToAmount, true
}

// HasToAmount returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasToAmount() bool {
	if o != nil && !IsNil(o.ToAmount) {
		return true
	}

	return false
}

// SetToAmount gets a reference to the given string and assigns it to the ToAmount field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetToAmount(v string) {
	o.ToAmount = &v
}

// GetToAsset returns the ToAsset field value if set, zero value otherwise.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetToAsset() string {
	if o == nil || IsNil(o.ToAsset) {
		var ret string
		return ret
	}
	return *o.ToAsset
}

// GetToAssetOk returns a tuple with the ToAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) GetToAssetOk() (*string, bool) {
	if o == nil || IsNil(o.ToAsset) {
		return nil, false
	}
	return o.ToAsset, true
}

// HasToAsset returns a boolean if a field has been set.
func (o *UmfuturesGetConvertOrderStatusV1Resp) HasToAsset() bool {
	if o != nil && !IsNil(o.ToAsset) {
		return true
	}

	return false
}

// SetToAsset gets a reference to the given string and assigns it to the ToAsset field.
func (o *UmfuturesGetConvertOrderStatusV1Resp) SetToAsset(v string) {
	o.ToAsset = &v
}

func (o UmfuturesGetConvertOrderStatusV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UmfuturesGetConvertOrderStatusV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.FromAmount) {
		toSerialize["fromAmount"] = o.FromAmount
	}
	if !IsNil(o.FromAsset) {
		toSerialize["fromAsset"] = o.FromAsset
	}
	if !IsNil(o.InverseRatio) {
		toSerialize["inverseRatio"] = o.InverseRatio
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.OrderStatus) {
		toSerialize["orderStatus"] = o.OrderStatus
	}
	if !IsNil(o.Ratio) {
		toSerialize["ratio"] = o.Ratio
	}
	if !IsNil(o.ToAmount) {
		toSerialize["toAmount"] = o.ToAmount
	}
	if !IsNil(o.ToAsset) {
		toSerialize["toAsset"] = o.ToAsset
	}
	return toSerialize, nil
}

type NullableUmfuturesGetConvertOrderStatusV1Resp struct {
	value *UmfuturesGetConvertOrderStatusV1Resp
	isSet bool
}

func (v NullableUmfuturesGetConvertOrderStatusV1Resp) Get() *UmfuturesGetConvertOrderStatusV1Resp {
	return v.value
}

func (v *NullableUmfuturesGetConvertOrderStatusV1Resp) Set(val *UmfuturesGetConvertOrderStatusV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableUmfuturesGetConvertOrderStatusV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableUmfuturesGetConvertOrderStatusV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUmfuturesGetConvertOrderStatusV1Resp(val *UmfuturesGetConvertOrderStatusV1Resp) *NullableUmfuturesGetConvertOrderStatusV1Resp {
	return &NullableUmfuturesGetConvertOrderStatusV1Resp{value: val, isSet: true}
}

func (v NullableUmfuturesGetConvertOrderStatusV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUmfuturesGetConvertOrderStatusV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


