/*
Binance Algorithmic Trading API

OpenAPI specification for Binance exchange - Algo API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package algo

import (
	"encoding/json"
)

// checks if the AlgoGetAlgoFuturesOpenOrdersV1Resp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlgoGetAlgoFuturesOpenOrdersV1Resp{}

// AlgoGetAlgoFuturesOpenOrdersV1Resp struct for AlgoGetAlgoFuturesOpenOrdersV1Resp
type AlgoGetAlgoFuturesOpenOrdersV1Resp struct {
	Orders []AlgoGetAlgoFuturesHistoricalOrdersV1RespOrdersInner `json:"orders,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewAlgoGetAlgoFuturesOpenOrdersV1Resp instantiates a new AlgoGetAlgoFuturesOpenOrdersV1Resp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlgoGetAlgoFuturesOpenOrdersV1Resp() *AlgoGetAlgoFuturesOpenOrdersV1Resp {
	this := AlgoGetAlgoFuturesOpenOrdersV1Resp{}
	return &this
}

// NewAlgoGetAlgoFuturesOpenOrdersV1RespWithDefaults instantiates a new AlgoGetAlgoFuturesOpenOrdersV1Resp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlgoGetAlgoFuturesOpenOrdersV1RespWithDefaults() *AlgoGetAlgoFuturesOpenOrdersV1Resp {
	this := AlgoGetAlgoFuturesOpenOrdersV1Resp{}
	return &this
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) GetOrders() []AlgoGetAlgoFuturesHistoricalOrdersV1RespOrdersInner {
	if o == nil || IsNil(o.Orders) {
		var ret []AlgoGetAlgoFuturesHistoricalOrdersV1RespOrdersInner
		return ret
	}
	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) GetOrdersOk() ([]AlgoGetAlgoFuturesHistoricalOrdersV1RespOrdersInner, bool) {
	if o == nil || IsNil(o.Orders) {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) HasOrders() bool {
	if o != nil && !IsNil(o.Orders) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given []AlgoGetAlgoFuturesHistoricalOrdersV1RespOrdersInner and assigns it to the Orders field.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) SetOrders(v []AlgoGetAlgoFuturesHistoricalOrdersV1RespOrdersInner) {
	o.Orders = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AlgoGetAlgoFuturesOpenOrdersV1Resp) SetTotal(v int32) {
	o.Total = &v
}

func (o AlgoGetAlgoFuturesOpenOrdersV1Resp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlgoGetAlgoFuturesOpenOrdersV1Resp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Orders) {
		toSerialize["orders"] = o.Orders
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableAlgoGetAlgoFuturesOpenOrdersV1Resp struct {
	value *AlgoGetAlgoFuturesOpenOrdersV1Resp
	isSet bool
}

func (v NullableAlgoGetAlgoFuturesOpenOrdersV1Resp) Get() *AlgoGetAlgoFuturesOpenOrdersV1Resp {
	return v.value
}

func (v *NullableAlgoGetAlgoFuturesOpenOrdersV1Resp) Set(val *AlgoGetAlgoFuturesOpenOrdersV1Resp) {
	v.value = val
	v.isSet = true
}

func (v NullableAlgoGetAlgoFuturesOpenOrdersV1Resp) IsSet() bool {
	return v.isSet
}

func (v *NullableAlgoGetAlgoFuturesOpenOrdersV1Resp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlgoGetAlgoFuturesOpenOrdersV1Resp(val *AlgoGetAlgoFuturesOpenOrdersV1Resp) *NullableAlgoGetAlgoFuturesOpenOrdersV1Resp {
	return &NullableAlgoGetAlgoFuturesOpenOrdersV1Resp{value: val, isSet: true}
}

func (v NullableAlgoGetAlgoFuturesOpenOrdersV1Resp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlgoGetAlgoFuturesOpenOrdersV1Resp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


